#ifndef SSSPLAYER_APP_PATHS_H
#define SSSPLAYER_APP_PATHS_H

/* Shared data root for music settings and video network/history. */
#define VITAMEDIADECK_DATA_DIR "ux0:data/SSSPlayer"
#define VITAMEDIADECK_NETWORK_DIR VITAMEDIADECK_DATA_DIR "/network"
#define VITAMEDIADECK_KNOWN_HOSTS_PATH VITAMEDIADECK_NETWORK_DIR "/known_hosts"
#define VITAMEDIADECK_NETWORK_PASSWORDS_PATH VITAMEDIADECK_NETWORK_DIR "/passwords.txt"
#define VITAMEDIADECK_SESSION_LOG_PATH VITAMEDIADECK_DATA_DIR "/session_log.txt"

#define SSSPLAYER_DATA_DIR VITAMEDIADECK_DATA_DIR

#endif
